### ISSUE TITLE
error in sCCA with cross-validation

### ISSUE THREAD

**Issue by hitrp** [acsala/sRDA#2]
I just encounter one problem when preforming 

CCA.res <- sCCA(predictor = x, predicted = y, nonzero = c(5,10,15),
ridge_penalty = c(0.1,1), penalization = "enet", cross_validate = TRUE,
parallel_CV = TRUE)

Cross valdiation function on multiple cores is called,
          number of detected cores on this work station: 8 
Error in h(simpleError(msg, call)) : 
 error in evaluating the argument 'x' in selecting a method for function 'as.matrix': non-numeric argument to binary operator

while this works for me:
cca.res <- sCCA(x,y,nonzero = 3,ridge_penalty = 1,penalization = "enet",multiple_LV  = TRUE,nr_LVs = 3)

any suggestion to this？

**Comment by acsala** [comment]
Can you share your Session info please?

**Comment by hitrp** [comment]
![image](https://github.com/acsala/sRDA/assets/30931150/1ba9e6be-5c9c-4e95-b362-4c4fded01fad)

**Comment by acsala** [comment]
Thank you for sharing your setup.

For the sRDA package, please use R 3.5 as specified here https://github.com/acsala/sRDA#session-info

If you'd rather stick to your current R version, you could try out the sparse PLS path modeling package, with which you can run sRDA by specifying the path modeling parameters: https://github.com/acsala/sPLSPM
